### ISSUE TITLE
verifyIdToken throws 'Null check operator used on a null value'

### ISSUE THREAD

**Issue by rezmeplxrf** [invertase/dart_firebase_admin#64]
I get "Null check operator used on a null value" when trying to verify the idtoken issued from a web firebase sdk (official).

## StackTrace
#0      new DecodedIdToken.fromMap (package:dart_firebase_admin/src/auth/token_verifier.dart:318:48)
#1      FirebaseTokenVerifier.verifyJWT (package:dart_firebase_admin/src/auth/token_verifier.dart:82:43)
<asynchronous suspension>
#2      _BaseAuth.verifyIdToken (package:dart_firebase_admin/src/auth/base_auth.dart:360:28)
<asynchronous suspension>
#3      FirebaseRepository.verifyIdToken (package:insightsentry_core/src/google/firebase.dart:56:22)
<asynchronous suspension>
#4      main (file:///Users/rezmeplx/Projects/insight_sentry/core/test/idtoken.dart:6:18)
idtoken.dart:6
<asynchronous suspension>

**Comment by rezmeplxrf** [comment]
Here's the example json data passed to DecodedIdToken class:

{iss: https://securetoken.google.com/myproject, aud: myprojectId, auth_time: 1732417815, user_id: Ek89AbErVLTkIFfqBXV5FkKunmi1, sub: Ek89AbErVLTkIFfqBXV5FkKunmi1, iat: 1732417815, exp: 1732421415, email: example@gmail.com, email_verified: true, firebase: {identities: {email: [example@gmail.com]}, sign_in_provider: password}}
